name: Node CI/CD

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: |
          touch .env.production.local
          echo REACT_APP_SERVER_PREFIX=${{ secrets.PRODUCTION_SERVER_PREFIX }} >> .env.production.local
          echo REACT_APP_TEST_SERVER_PREFIX=${{ secrets.PRODUCTION_TEST_SERVER_PREFIX }} >> .env.production.local
          echo REACT_APP_SOCKET_SERVER_PREFIX=${{ secrets.PRODUCTION_SOCKET_SERVER_PREFIX }} >> .env.production.local
          npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
#          EXCLUDE: "/dist/, /node_modules/"
